meta_product_name: "Flavie SEREN-ROSSO"
meta_title: "Flavie SEREN-ROSSO - Pâtissière"
meta_description: "Portfolio de Pâtisserie - Passionnée de Pâtisserie depuis toujours, je crée et revisite des pâtisseries, gourmandes et généreuses"
meta_image: "Bannière_1200px.png" # should exist in `app/assets/images/`
